# Generated by Django 5.2.3 on 2025-06-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
    ]
